### PR TITLE
base logo and little formattind added

### PR DESCRIPTION
**Pull request by Lytiuga**
Still can't add a Award icon

### CODE REVIEW

**Comment by namulford** [comment]
Hey Mike,

I had to review the SaveTheChallengeForm changes you merged previously because it was not working.  Let's get the form working first and then I will merge the logo

Thanks!!

**Comment by Lytiuga** [comment]
what do you mean "not working"? 
Button collect the data from all input fields and log it into the console like this "namename|goalGoal|UserUser|Instructuion"

**Comment by namulford** [comment]
The page errors out, and does not display the form.

**Comment by Lytiuga** [comment]
Screenshot
[https://www.dropbox.com/s/cs4384u7xprjs35/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-08-22%20%D0%B2%208.56.12%20PM.png?dl=0]

**Comment by namulford** [comment]
#2 
screen shot 2018-08-22 at 10 58 28 pm

**Comment by Lytiuga** [comment]
https://pasteboard.co/HArnTut.png

**Comment by Lytiuga** [comment]
Do you have a semantic-ui-react installed?

**Comment by namulford** [comment]
Sure do!

**Comment by Lytiuga** [comment]
this error code tells me that it can't find the module, 
Do you have installed as written - semantic-ui-react, not semantic-ui, and this module is installed inside your progress-tracker folder?

**Comment by namulford** [comment]
Yes, I have semantic-ui-react installed.

**Review by jscottchapman — COMMENTED** [review]
LGTM

**Pull request merged**
